- src/Components/LoginPage.jsx
- src/Components/ProfilePage.js
fixed it so you can now submit the forms on the login page and the profile page when you hit the enter key and not just when you click on the button
resolves #34
> Allow submit on enter

- src/Components/LoginPage.jsx
when the user hits enter on the login page it now submits again
> make submit on enter work again

- src/App.js
- src/Components/CreateEvent.jsx
- src/Components/MenuBar.js
- src/Components/ViewEvent.css
- src/Components/ViewEvent.jsx
closes #54 
Create the initial view event page.  will need to update when we integrate the zoom stuff.  might also want to add ability to see who the participants are for that event.
> View event page

- src/Components/ViewEvent.jsx
fixed an issue there the buttons werent named correctly
> fix issue with names of buttons

- src/Components/CreateAccount.jsx
- src/Components/CreateEvent.jsx
- src/Components/LoginPage.jsx
- src/Components/ProfilePage.js
- src/Components/ViewEvent.jsx
- src/RefreshToken.js
closes #64 
closes #60 
Add JWT authentication to the login, profile, create account, create event and view event pages.  You can only perform the actions if you are authenticated except logging in and creating an account.
> Authentication in gui

- package-lock.json
- package.json
- src/Components/ProfilePage.js
give the user the ability to edit their profile picture when viewing their profile picture
closes #63
> Edit profile picture

- src/Components/CreateAccount.jsx
- src/Components/CreateEvent.jsx
- src/Components/Environment.jsx
- src/Components/LoginPage.jsx
- src/Components/ProfilePage.js
- src/Components/ViewEvent.jsx
> Adding in environment based urls

- package-lock.json
- package.json
- src/App.js
- src/Components/CreateAccount.jsx
- src/Components/CreateEvent.jsx
- src/Components/LoginPage.jsx
- src/Components/ProfilePage.js
- src/Components/ViewEvent.jsx
closes #72 
the alert pops up and displays a message to the user
> have an alert popup for the user is they fail to login, create, edit or view a profile or create, view or edit an event

- src/Components/ViewEvent.jsx
if no class id is passed in through the state dont break the page and instead load the view event page with no data.
closes #71
> Fix view event issue

- src/Components/ClassCalendar.css
- src/Components/ClassCalendar.jsx
- src/Components/CreateAccount.css
- src/Components/CreateAccount.jsx
- src/Components/CreateEvent.css
- src/Components/CreateEvent.jsx
- src/Components/LandingPage.jsx
- src/Components/LoginApp.css
- src/Components/LoginPage.jsx
- src/Components/MenuBar.js
- src/Components/ProfilePage.css
- src/Components/ProfilePage.js
- src/Components/ViewEvent.jsx
Closes #57 and Closes #78 
Made all the pages responsive.  They should all look good, they looked good when using the dev tools in Google Chrome for different screen sizes.
Also changed some of the text input types to email so it works better on a phone.
Cleanup white spaces and other general cleanup.
Fix issue with multiply defined class names in the css files.
Fix the issue with the date picker not working on the create account page
> Make all pages responsive

- src/App.js
- src/Components/ChangePassword.css
- src/Components/ChangePassword.js
- src/Components/MenuBar.js
> Adding change password functionality to UI

- src/Components/CreateAccount.jsx
email_address is under user not under refresh
> email_address is under user not under refresh

- src/Components/CalDate.js
- src/Components/Calendar.jsx
- src/Components/ChangePassword.js
- src/Components/ConfirmForgotPassword.js
- src/Components/CreateAccount.jsx
- src/Components/CreateEvent.jsx
- src/Components/ForgotPassword.jsx
- src/Components/LoginPage.jsx
- src/Components/ViewEvent.jsx
dont let users access pages they should be able to by typing the url in manually
users used to be able to manually type in a url and go to that page even if we didnt want them to such as when they are logged in or not logged in.  this fixes that
> dont let users access pages they should be able to by typing the url in manually

- src/Components/Calendar.css
- src/Components/Calendar.jsx
> fixing calendar length

- src/Components/CreateAccount.css
- src/Components/CreateAccount.jsx
> update the background for create account to show up better on small screens

- src/App.js
- src/Components/Calendar.jsx
- src/Components/CalendarEvent.js
excluding other in-flight changes this should remove all code smells other than 1 for service workers.
> Fixing code smells with sonar cloud

- src/Components/LoginApp.css
> Fixing login button size on prod

- src/Components/CreateAccount.jsx
closes #123 
when creating an account it now says role until a role is selected then that option disappears for the user
> change default selected to dummy that disapears when user selects a real role

- src/Components/CreateAccount.css
- src/Components/CreateAccount.jsx
closes #102 
update the create account and the choose file button on the create account page to be the same design as the login page button.
> Update create account buttons

- src/Components/LandingPage.css
- src/Components/LandingPage.jsx
make the landing page response and show up appropriately on small phone screens
> Make landing page responsive

- src/Components/Roster.css
- src/Components/Roster.jsx
make the roster page responsive
> make the roster page responsive

- src/Components/CreateEvent.css
- src/Components/CreateEvent.jsx
closes #140 
created a combobox populated with the rosters in the database and lets the user select a roster to associate with a class 
NOTE: this will require some backend changes for it to fully work
> lets user select a roster when creating a class

- src/Components/Calendar.jsx
- src/RefreshToken.js
if the token is invalid we now call logout so the data stored in session storage is cleared to prevent the flashing back and forth between login and calendar pages
closes #150
> Fix the Token Timeout Unusable website Issue

- package-lock.json
- src/Components/Calendar.jsx
- src/Components/CreateEvent.jsx
- src/Components/LandingPage.jsx
- src/Components/Roster.jsx
- src/Components/ViewEvent.jsx
associated with backend pull request #88
> updated frontend to use event instead of class
